name: Deploy AstroWind to Cloudflare Pages

on:
  push:
    branches:
      - main
    paths:
      - "src/content/post/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Cloudflare Deploy
        run: |
          curl -X POST "${{ secrets.CF_DEPLOY_HOOK }}"

      - name: Notify Telegram on Success
        if: success()
        run: |
          DEPLOY_URL="https://bug.edu.vn"
          MESSAGE=$(printf "‚úÖ Build v√† Deploy Th√†nh C√¥ng!\n\nüåê <a href=\"%s\">Xem website</a>\nüïì <i>%s</i>" "$DEPLOY_URL")

          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="$MESSAGE" \
            -d parse_mode="HTML"




